'use client';

import { useEffect, useRef, useState } from 'react';
import { nutritionApi } from '@/lib/user/api-client';
import type { MealType, PersonalFood } from '@/lib/user/types';
import { FoodNutritionTool } from './FoodNutritionTool';
import { PersonalFoodForm } from './PersonalFoodForm';

type Mode = 'menu' | 'search' | 'scan' | 'mine' | 'create';
const number = (value: number, locale: 'fr' | 'en') => new Intl.NumberFormat(locale === 'fr' ? 'fr-FR' : 'en-US', { maximumFractionDigits: 1 }).format(value);

export function AddFoodDialog({ locale, date, mealType, onClose, onAdded }: { locale: 'fr' | 'en'; date: string; mealType: MealType; onClose: () => void; onAdded: () => Promise<void> }) {
  const french = locale === 'fr'; const [mode, setMode] = useState<Mode>('menu'); const [foods, setFoods] = useState<PersonalFood[]>([]); const [selected, setSelected] = useState<PersonalFood | null>(null); const [quantity, setQuantity] = useState(100); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const closeRef = useRef<HTMLButtonElement>(null);
  const loadFoods = async () => { try { setFoods(await nutritionApi.personalFoods()); } catch { setError(french ? 'Impossible de charger vos aliments.' : 'Unable to load your foods.'); } };
  useEffect(() => { closeRef.current?.focus(); void loadFoods(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape); }, [onClose]);
  const addPersonal = async () => { if (!selected || !Number.isFinite(quantity) || quantity <= 0) return; setBusy(true); setError(''); try { await nutritionApi.createEntry({ date, mealType, sourceType: 'PERSONAL', personalFoodId: selected.id, consumedAmount: quantity }); await onAdded(); onClose(); } catch { setError(french ? 'Impossible d’ajouter cet aliment.' : 'Unable to add this food.'); } finally { setBusy(false); } };
  const choices: Array<[Mode, string]> = [['search', french ? 'Rechercher un aliment' : 'Search for food'], ['scan', french ? 'Scanner un produit' : 'Scan a product'], ['mine', french ? 'Mes aliments' : 'My foods'], ['create', french ? 'Créer un aliment' : 'Create custom food']];
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 p-0 sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="add-food-title"><div className="max-h-[95vh] w-full max-w-4xl overflow-y-auto rounded-t-3xl bg-white p-4 shadow-2xl sm:rounded-3xl sm:p-6">
    <div className="sticky top-0 z-10 flex items-center justify-between gap-4 border-b border-slate-200 bg-white pb-4"><div><h2 id="add-food-title" className="text-xl font-bold">{french ? 'Ajouter un aliment' : 'Add food'}</h2><p className="text-sm text-slate-500">{date}</p></div><button ref={closeRef} type="button" onClick={onClose} aria-label={french ? 'Fermer' : 'Close'} className="rounded-full border border-slate-300 px-4 py-2 font-bold">×</button></div>
    <div className="mt-4 flex flex-wrap gap-2">{choices.map(([key, label]) => <button key={key} type="button" onClick={() => { setMode(key); setSelected(null); }} aria-pressed={mode === key} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${mode === key ? 'bg-brand-700 text-white' : 'border border-slate-300'}`}>{label}</button>)}</div>
    {mode === 'menu' ? <p className="mt-8 rounded-2xl bg-slate-50 p-5 text-slate-600">{french ? 'Choisissez une méthode pour ajouter votre aliment.' : 'Choose how you want to add your food.'}</p> : null}
    {mode === 'search' || mode === 'scan' ? <FoodNutritionTool locale={locale} initialMode={mode} diaryContext={{ date, mealType }} onAdded={async () => { await onAdded(); onClose(); }} onCreateCustom={() => setMode('create')} /> : null}
    {mode === 'create' ? <div className="mt-5"><PersonalFoodForm locale={locale} onSaved={(food) => { setFoods((current) => [food, ...current]); setSelected(food); setQuantity(food.servingSize); setMode('mine'); }} /></div> : null}
    {mode === 'mine' ? <section className="mt-6" aria-labelledby="my-foods-title"><h3 id="my-foods-title" className="text-lg font-bold">{french ? 'Mes aliments' : 'My foods'}</h3>{foods.length ? <div className="mt-3 grid gap-3 sm:grid-cols-2">{foods.map((food) => <button type="button" key={food.id} onClick={() => { setSelected(food); setQuantity(food.servingSize); }} className={`rounded-2xl border p-4 text-left ${selected?.id === food.id ? 'border-brand-700 bg-brand-50 ring-2 ring-brand-100' : 'border-slate-200'}`}><strong>{food.name}</strong>{food.brand ? <span className="block text-sm text-slate-500">{food.brand}</span> : null}<span className="mt-2 block text-sm">{number(food.calories, locale)} kcal · P {number(food.protein, locale)} g · G {number(food.carbs, locale)} g · L {number(food.fat, locale)} g</span><span className="block text-xs text-slate-500">{french ? 'Pour' : 'Per'} {food.servingSize} {food.servingUnit}</span></button>)}</div> : <p className="mt-3 text-slate-500">{french ? 'Aucun aliment personnel.' : 'No custom foods yet.'}</p>}
      {selected ? <div className="mt-5 rounded-2xl bg-slate-50 p-4"><h4 className="font-bold">{selected.name}</h4><label className="mt-3 block text-sm font-bold">{french ? 'Quantité consommée' : 'Amount consumed'} ({selected.servingUnit})<input autoFocus type="number" min="0.01" step="any" value={quantity} onChange={(e) => setQuantity(e.target.valueAsNumber)} className="mt-2 w-full max-w-xs rounded-xl border border-slate-300 px-4 py-3" /></label><p className="mt-3 text-sm text-slate-600">{french ? 'Repas présélectionné' : 'Preselected meal'}: {mealType}</p><button type="button" disabled={busy || !Number.isFinite(quantity) || quantity <= 0} onClick={() => void addPersonal()} className="mt-4 rounded-xl bg-brand-700 px-5 py-3 font-bold text-white disabled:opacity-50">{busy ? '…' : french ? 'Ajouter' : 'Add'}</button></div> : null}
    </section> : null}
    {error ? <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p> : null}
  </div></div>;
}
