import type { ReactNode } from 'react';
import { LegalPageLayout } from '@/components/legal/LegalPageLayout';
import type { LegalPageKey, Locale } from '@/lib/i18n/routing';

const EN_DATE = 'Last updated: August 8, 2026';
const FR_DATE = 'Dernière mise à jour : 8 août 2026';
const contact = <a href="mailto:support@2dolist.fr">support@2dolist.fr</a>;

const Section = ({ title, children }: { title: string; children: ReactNode }) => <section><h2>{title}</h2>{children}</section>;
const Items = ({ children }: { children: ReactNode }) => <ul>{children}</ul>;

const enTerms = <>
  <Section title="1. Operator and acceptance"><p>BodyTrainingGuide.com is operated by 2DOLIST USA LLC, a Florida limited liability company. By accessing or using the website, you agree to these Terms of Use. If you do not agree, do not use the website.</p></Section>
  <Section title="2. General informational purpose"><p>BodyTrainingGuide provides general informational and educational content about strength training, exercise, fitness, nutrition, calories, macronutrients, dietary supplements, and sports equipment. The content is not individualized professional advice and is not medical advice, diagnosis, treatment, prescription, medical care, or personalized medical nutrition advice.</p></Section>
  <Section title="3. Exercise risks and individual responsibility"><p>Exercise and strength training involve inherent risks. Abilities, health, experience, and needs differ between individuals. Descriptions of exercises, sets, repetitions, loads, volume, and programs are general information; they do not guarantee that an exercise or program is suitable for a particular person.</p><p>You remain responsible for assessing what is appropriate for your circumstances, using proper technique and equipment, stopping if you experience pain or concerning symptoms, and consulting a qualified professional when appropriate.</p></Section>
  <Section title="4. Nutrition and calculators"><p>Nutrition information is general. Values for calories, protein, carbohydrates, fats, hydration, and energy needs may be estimates and are not personalized medical nutrition prescriptions.</p><p>Results from calculators—including calorie, macro, TDEE, BMI, body-fat, 1RM, protein, and training-volume calculators—are estimates based on the information and formulas used. They are not medical measurements, diagnoses, or personalized prescriptions.</p></Section>
  <Section title="5. Dietary supplements"><p>BodyTrainingGuide may publish educational information about dietary supplements and their ingredients. This does not mean a supplement is suitable for every person. Supplements may affect individuals differently and may interact with health conditions, medication, or other substances. Review the manufacturer’s current information and warnings and seek qualified advice when appropriate.</p><p>Unless expressly stated otherwise, BodyTrainingGuide and 2DOLIST USA LLC are not the manufacturer or seller of supplements discussed on the website. No supplement content is intended to claim that a product diagnoses, treats, cures, or prevents disease.</p></Section>
  <Section title="6. No guaranteed results"><p>BodyTrainingGuide does not guarantee muscle gain, strength gain, weight loss, fat loss, athletic performance, physical transformation, or the time required to achieve any result. Outcomes vary according to many factors, including health, training history, consistency, nutrition, recovery, and individual response.</p></Section>
  <Section title="7. Products and third-party merchants"><p>BodyTrainingGuide is a content publisher. It may present, compare, test, review, or link to products, display a price, or provide an affiliate link. When you are redirected to an external merchant, BodyTrainingGuide does not conduct the sale unless expressly stated otherwise.</p><p>The sale contract, payment, current price, shipping, returns, refunds, warranty, and customer service are handled by the third-party merchant under that merchant’s terms. Product information and prices may change; verify current information with the merchant before purchasing.</p></Section>
  <Section title="8. Affiliate links, advertising, and sponsored content"><p>Some links may be affiliate links. If you click and complete a qualifying purchase or action with a merchant, 2DOLIST USA LLC may receive a commission or other compensation, normally without additional cost charged by BodyTrainingGuide to you. An affiliate link does not make BodyTrainingGuide the seller.</p><p>The website may display advertising or sponsored content. Commercial content intended to resemble editorial content will be identified as “Advertisement” or “Sponsored,” as appropriate. Compensation does not remove your responsibility to evaluate products and third-party claims.</p></Section>
  <Section title="9. Third-party websites"><p>Links to third-party websites are provided for information and convenience. 2DOLIST USA LLC does not control their availability, content, privacy practices, security, products, or terms and is not responsible for them. Your dealings with a third party are between you and that third party.</p></Section>
  <Section title="10. Intellectual property and acceptable use"><p>Unless otherwise indicated, website content is owned by or licensed to 2DOLIST USA LLC and is protected by applicable intellectual-property laws. You may use the website for personal, non-commercial purposes. You may not unlawfully copy, republish, scrape, disrupt, reverse engineer, or misuse the website or its content.</p></Section>
  <Section title="11. Availability and changes"><p>We may correct, update, suspend, or remove content or functionality at any time. We do not promise that the website will always be uninterrupted, error-free, complete, or current. We may update these Terms by publishing a revised version and update date.</p></Section>
  <Section title="12. Disclaimer and limitation of liability"><p>To the fullest extent permitted by applicable law, the website and its content are provided “as is” and “as available,” without warranties of accuracy, fitness for a particular purpose, availability, or results. You use the website and act on its content at your own risk.</p><p>To the fullest extent permitted by law, 2DOLIST USA LLC and its members, personnel, and service providers will not be liable for indirect, incidental, special, consequential, or punitive damages, or for losses arising from reliance on content, exercise, nutrition, supplements, products, third-party merchants, third-party sites, or website interruption. Nothing in these Terms excludes liability or rights that cannot lawfully be excluded or limited.</p></Section>
  <Section title="13. Applicable law"><p>These Terms are governed by the laws of the State of Florida and applicable federal law, without regard to conflict-of-law principles.</p><p>Mandatory rights or protections that cannot lawfully be waived and that apply to a user in their jurisdiction remain unaffected.</p></Section>
  <Section title="14. Contact"><p>Questions about these Terms may be sent to {contact}.</p></Section>
</>;

const frTerms = <>
  <Section title="1. Exploitant et acceptation"><p>BodyTrainingGuide.com est exploité par 2DOLIST USA LLC, société à responsabilité limitée de droit de Floride. En accédant au site ou en l’utilisant, vous acceptez les présentes Conditions d’utilisation. Si vous ne les acceptez pas, n’utilisez pas le site.</p></Section>
  <Section title="2. Finalité générale d’information"><p>BodyTrainingGuide fournit des contenus généraux d’information et d’éducation relatifs notamment à la musculation, l’entraînement, le fitness, les exercices, la nutrition, les calories, les macronutriments, les compléments alimentaires et le matériel sportif. Ces contenus ne constituent pas des conseils professionnels individualisés, ni un avis médical, un diagnostic, un traitement, une prescription, une prise en charge médicale ou un conseil nutritionnel médical personnalisé.</p></Section>
  <Section title="3. Risques liés aux exercices et responsabilité individuelle"><p>L’exercice physique et la musculation comportent des risques inhérents. Les capacités, la santé, l’expérience et les besoins diffèrent selon les individus. Les descriptions d’exercices, de séries, de répétitions, de charges, de volumes et de programmes sont des informations générales. Elles ne garantissent pas qu’un exercice ou programme soit adapté à une personne particulière.</p><p>Vous demeurez responsable d’évaluer ce qui est approprié à votre situation, d’utiliser une technique et un matériel adaptés, de vous arrêter en cas de douleur ou de symptôme préoccupant et de consulter un professionnel qualifié lorsque cela est nécessaire.</p></Section>
  <Section title="4. Nutrition et calculateurs"><p>Les informations nutritionnelles sont générales. Les valeurs concernant notamment les calories, protéines, glucides, lipides, l’hydratation et les besoins énergétiques peuvent être des estimations et ne constituent pas une prescription nutritionnelle médicale personnalisée.</p><p>Les résultats de calculateurs de calories, macros, TDEE, BMI/IMC, masse grasse, 1RM, protéines ou volume d’entraînement sont des estimations fondées sur les informations et formules utilisées. Ils ne constituent ni des mesures médicales, ni des diagnostics, ni des prescriptions personnalisées.</p></Section>
  <Section title="5. Compléments alimentaires"><p>BodyTrainingGuide peut publier des informations éducatives sur les compléments alimentaires et leurs ingrédients. Ces contenus ne signifient pas qu’un complément est adapté à chaque personne. Les compléments peuvent avoir des effets différents selon les individus et interagir avec certaines pathologies, des médicaments ou d’autres substances. Consultez les informations et avertissements actuels du fabricant et sollicitez un avis qualifié lorsque cela est approprié.</p><p>Sauf indication expresse contraire, BodyTrainingGuide et 2DOLIST USA LLC ne sont ni le fabricant ni le vendeur des compléments abordés sur le site. Aucun contenu relatif à un complément ne vise à affirmer qu’un produit permet de diagnostiquer, traiter, guérir ou prévenir une maladie.</p></Section>
  <Section title="6. Absence de résultats garantis"><p>BodyTrainingGuide ne garantit aucun résultat concernant notamment la prise de muscle, le gain de force, la perte de poids, la perte de graisse, les performances sportives, la transformation physique ou le délai nécessaire pour atteindre un résultat. Les résultats varient selon de nombreux facteurs, notamment la santé, l’expérience, la régularité, la nutrition, la récupération et la réponse individuelle.</p></Section>
  <Section title="7. Produits et marchands tiers"><p>BodyTrainingGuide est un éditeur de contenu. Il peut présenter, comparer, tester ou commenter des produits, afficher un prix, proposer un lien ou un lien affilié. Lorsque vous êtes redirigé vers un marchand externe, BodyTrainingGuide ne réalise pas la vente, sauf indication expresse contraire.</p><p>Le contrat de vente, le paiement, le prix actuel, l’expédition, les retours, les remboursements, la garantie et le service après-vente relèvent du marchand tiers et de ses conditions. Les informations et prix peuvent évoluer : vérifiez les informations actuelles auprès du marchand avant tout achat.</p></Section>
  <Section title="8. Liens d’affiliation, publicité et contenus sponsorisés"><p>Certains liens peuvent être des liens affiliés. Si vous cliquez puis réalisez un achat ou une autre action admissible auprès du marchand, 2DOLIST USA LLC peut percevoir une commission ou une autre rémunération, normalement sans coût supplémentaire facturé par BodyTrainingGuide. Un lien affilié ne fait pas de BodyTrainingGuide le vendeur.</p><p>Le site peut afficher de la publicité ou du contenu sponsorisé. Un contenu commercial ressemblant à un contenu éditorial sera identifié, selon le cas, comme « Publicité » ou « Sponsorisé ». Une rémunération ne vous dispense pas d’évaluer les produits et affirmations de tiers.</p></Section>
  <Section title="9. Sites tiers"><p>Les liens vers des sites tiers sont fournis à titre informatif et pratique. 2DOLIST USA LLC ne contrôle pas leur disponibilité, contenu, pratiques de confidentialité, sécurité, produits ou conditions et n’en est pas responsable. Vos relations avec un tiers se déroulent entre ce tiers et vous.</p></Section>
  <Section title="10. Propriété intellectuelle et utilisation acceptable"><p>Sauf indication contraire, les contenus du site appartiennent à 2DOLIST USA LLC ou lui sont concédés sous licence et sont protégés par les lois applicables. Vous pouvez utiliser le site à des fins personnelles et non commerciales. Vous ne pouvez pas copier, republier, extraire, perturber, désassembler ou détourner illicitement le site ou son contenu.</p></Section>
  <Section title="11. Disponibilité et modifications"><p>Nous pouvons corriger, mettre à jour, suspendre ou supprimer des contenus ou fonctionnalités. Nous ne garantissons pas un site toujours disponible, sans erreur, exhaustif ou à jour. Nous pouvons modifier les présentes Conditions en publiant une version révisée et sa nouvelle date.</p></Section>
  <Section title="12. Exclusion de garanties et limitation de responsabilité"><p>Dans toute la mesure permise par la législation applicable, le site et son contenu sont fournis « en l’état » et « selon disponibilité », sans garantie d’exactitude, d’adaptation à un objectif, de disponibilité ou de résultat. Vous utilisez le site et agissez sur la base de son contenu à vos propres risques.</p><p>Dans toute la mesure permise par la loi, 2DOLIST USA LLC, ses membres, son personnel et ses prestataires ne seront pas responsables des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs, ni des pertes résultant de la confiance accordée aux contenus, de l’exercice, de la nutrition, des compléments, des produits, des marchands ou sites tiers, ou d’une interruption du site. Aucune disposition n’exclut une responsabilité ou un droit ne pouvant légalement être exclu ou limité.</p></Section>
  <Section title="13. Droit applicable"><p>Les présentes Conditions sont régies par les lois de l’État de Floride et le droit fédéral américain applicable, sans préjudice des règles relatives aux conflits de lois.</p><p>Les droits ou protections impératifs dont un utilisateur bénéficie éventuellement en vertu d’une législation qui lui est applicable et auxquels il ne peut légalement être renoncé demeurent applicables.</p></Section>
  <Section title="14. Contact"><p>Vos questions relatives aux présentes Conditions peuvent être adressées à {contact}.</p></Section>
</>;
const enMedical = <>
  <Section title="General information only"><p>Information published by BodyTrainingGuide is for general informational and educational purposes only. BodyTrainingGuide is not a healthcare provider and does not provide diagnosis, treatment, prescriptions, personalized medical advice, physical therapy, or individualized medical nutrition care. Using the website does not create a doctor-patient or other healthcare professional-patient relationship.</p></Section>
  <Section title="Exercise and training"><p>Physical exercise and strength training have inherent risks, including injury and aggravation of existing conditions. Exercise descriptions and training programs cannot account for every person’s health, technique, environment, or ability. Stop exercising and seek appropriate assistance if you experience pain, faintness, breathing difficulty, chest discomfort, or other concerning symptoms.</p></Section>
  <Section title="When to seek qualified advice"><p>People with a medical condition, previous injury, cardiovascular issue, metabolic disease, chronic pain, pregnancy, medication use, or allergies should consider seeking advice from a qualified healthcare professional before making significant changes to training, diet, or supplementation. This is a contextual precaution, not a statement that every person must obtain medical clearance in every circumstance.</p></Section>
  <Section title="Nutrition, calculators, and supplements"><p>Nutrition information and calculator outputs are estimates, not medical measurements or personalized prescriptions. Supplements can affect people differently and may interact with conditions, medicines, or other substances. Follow current manufacturer warnings and consult an appropriate professional when needed. No content is intended to diagnose, treat, cure, or prevent disease.</p></Section>
  <Section title="Emergencies"><p>The website is not an emergency service. If you believe you are experiencing a medical emergency, contact the emergency services available in your location immediately.</p></Section>
  <Section title="No results guarantee"><p>No health, fitness, body-composition, performance, or timing result is promised. You remain responsible for decisions about your health and use of the information.</p></Section>
</>;
const frMedical = <>
  <Section title="Informations générales uniquement"><p>Les informations publiées par BodyTrainingGuide sont uniquement destinées à l’information et à l’éducation générale. BodyTrainingGuide n’est pas un prestataire de soins de santé et ne fournit pas de diagnostic, de traitement, de prescription, de conseil médical personnalisé, de physiothérapie ou de prise en charge nutritionnelle médicale individualisée. L’utilisation du site ne crée aucune relation médecin-patient ou professionnel de santé-patient.</p></Section>
  <Section title="Exercice et entraînement"><p>L’exercice physique et la musculation comportent des risques inhérents, notamment de blessure ou d’aggravation d’une pathologie existante. Les descriptions d’exercices et programmes ne peuvent tenir compte de la santé, de la technique, de l’environnement ou des capacités de chaque personne. Arrêtez l’exercice et recherchez une aide appropriée en cas de douleur, malaise, difficulté respiratoire, gêne thoracique ou autre symptôme préoccupant.</p></Section>
  <Section title="Quand solliciter un avis qualifié"><p>Les personnes présentant notamment une pathologie, des antécédents de blessure, un problème cardiovasculaire, une maladie métabolique, des douleurs chroniques, une grossesse, un traitement médicamenteux ou des allergies doivent envisager de demander l’avis d’un professionnel de santé qualifié avant de modifier significativement leur entraînement, alimentation ou supplémentation. Il s’agit d’une précaution adaptée au contexte, et non d’une obligation universelle de validation médicale en toute circonstance.</p></Section>
  <Section title="Nutrition, calculateurs et compléments"><p>Les informations nutritionnelles et résultats des calculateurs sont des estimations, et non des mesures médicales ou prescriptions personnalisées. Les compléments peuvent produire des effets différents et interagir avec des pathologies, médicaments ou substances. Respectez les avertissements actuels du fabricant et consultez un professionnel approprié si nécessaire. Aucun contenu ne vise à diagnostiquer, traiter, guérir ou prévenir une maladie.</p></Section>
  <Section title="Urgences"><p>Le site n’est pas un service d’urgence. Si vous pensez faire face à une urgence médicale, contactez immédiatement les services d’urgence disponibles dans votre lieu de résidence.</p></Section>
  <Section title="Absence de garantie de résultat"><p>Aucun résultat concernant la santé, le fitness, la composition corporelle, les performances ou le délai d’obtention d’un résultat n’est promis. Vous restez responsable de vos décisions de santé et de votre utilisation des informations.</p></Section>
</>;

const enAffiliate = <>
  <Section title="Affiliate relationships"><p>BodyTrainingGuide may participate in affiliate programs. Some links on the website may be affiliate links. If you click an affiliate link and then make a purchase or complete another qualifying action with the merchant, 2DOLIST USA LLC may receive a commission or other compensation.</p><p>Unless stated otherwise, that compensation creates no additional cost charged by BodyTrainingGuide to you.</p></Section>
  <Section title="Editorial independence"><p>Affiliate compensation does not guarantee a favorable review or result. We aim to distinguish editorial information from advertising or sponsored content. You should independently assess whether a product is appropriate for you.</p></Section>
  <Section title="The merchant is the seller"><p>The existence of an affiliate link does not make BodyTrainingGuide or 2DOLIST USA LLC the seller of the product. Unless expressly stated otherwise, the third-party merchant sets the price, takes payment, enters into the sale contract, and handles shipping, returns, refunds, warranties, and customer service. Prices and availability may change; check the retailer for current information.</p></Section>
  <Section title="Questions"><p>Questions about an affiliate relationship may be sent to {contact}.</p></Section>
</>;
const frAffiliate = <>
  <Section title="Relations d’affiliation"><p>BodyTrainingGuide peut participer à des programmes d’affiliation. Certains liens présents sur le site peuvent être des liens affiliés. Si vous cliquez sur un lien affilié puis réalisez un achat ou une autre action admissible auprès du marchand, 2DOLIST USA LLC peut percevoir une commission ou une autre rémunération.</p><p>Sauf indication contraire, cette rémunération n’entraîne pas de coût supplémentaire facturé par BodyTrainingGuide à l’utilisateur.</p></Section>
  <Section title="Indépendance éditoriale"><p>Une rémunération d’affiliation ne garantit pas un avis ou un résultat favorable. Nous cherchons à distinguer l’information éditoriale de la publicité et du contenu sponsorisé. Il vous appartient d’évaluer de manière indépendante si un produit vous convient.</p></Section>
  <Section title="Le marchand est le vendeur"><p>L’existence d’un lien affilié ne signifie pas que BodyTrainingGuide ou 2DOLIST USA LLC devient le vendeur du produit. Sauf indication expresse contraire, le marchand tiers fixe le prix, encaisse le paiement, conclut le contrat de vente et gère l’expédition, les retours, les remboursements, les garanties et le service après-vente. Les prix et disponibilités peuvent évoluer ; consultez le marchand pour obtenir les informations actuelles.</p></Section>
  <Section title="Questions"><p>Les questions relatives à une relation d’affiliation peuvent être adressées à {contact}.</p></Section>
</>;

const enPrivacy = <>
  <Section title="1. Who operates the website"><p>This Privacy Policy explains how 2DOLIST USA LLC, a Florida limited liability company, handles personal data in connection with BodyTrainingGuide.com.</p></Section>
  <Section title="2. Data we collect"><p>Depending on how you use the website, we may receive:</p><Items><li>information you submit, such as your email address and newsletter source when you subscribe, or information you send by email;</li><li>technical request data ordinarily transmitted online, such as IP address, browser and device information, requested URL, timestamps, and security or server logs;</li><li>administrative authentication data for authorized administrators; and</li><li>information a third-party merchant receives when you follow an external link, which is handled under that third party’s policy.</li></Items><p>The public contact page currently displays an unconnected form and does not submit its fields. Do not enter sensitive information into website forms.</p></Section>
  <Section title="3. How and why we use data"><p>We may use data to provide and secure the website, respond to messages, process newsletter requests, diagnose errors, prevent abuse, maintain records, comply with law, and establish or defend legal claims. Where required, the legal basis depends on the processing and may include consent, performance of a request, legitimate interests, or legal obligations.</p></Section>
  <Section title="4. Analytics and cookies"><p>The current public frontend does not intentionally load analytics, advertising pixels, or a consent-management platform. It does not set optional public-facing analytics or advertising cookies. Authorized administration uses an essential authentication cookie, and the administration editor uses browser local storage. See the Cookie Policy for details. If optional technologies are introduced, this policy and any required consent controls should be updated before they are enabled for affected users.</p></Section>
  <Section title="5. Sharing and international processing"><p>We may disclose data to hosting, infrastructure, security, email/newsletter, and professional service providers as needed to operate the service, and to authorities or other parties when required or permitted by law. Because the operator is in the United States and the website is international, data may be processed outside your country. Safeguards required by applicable law will be used where applicable.</p></Section>
  <Section title="6. Retention and security"><p>We retain personal data only as long as reasonably necessary for the relevant purpose, legal obligations, security, disputes, and enforcement. Retention varies by data type and context. We use reasonable technical and organizational measures, but no online system is completely secure.</p></Section>
  <Section title="7. Your privacy choices and rights"><p>Your rights depend on applicable law and the circumstances. Where applicable, they may include access, correction, deletion, restriction, objection, portability, withdrawal of consent, and certain rights concerning targeted advertising or data sharing. Withdrawing consent does not affect earlier lawful processing. We may need to verify a request and may retain information where legally permitted or required.</p></Section>
  <Section title="Users in the European Economic Area"><p>Where European data protection law applies to the processing of your personal data, you may have additional rights under applicable law, including rights of access, rectification, erasure, restriction, objection and data portability, as applicable.</p><p>Where processing relies on consent, you may withdraw that consent at any time.</p><p>The applicability of these rights depends on the circumstances of the processing and applicable law.</p></Section>
  <Section title="8. Children"><p>The website is not directed to children who are not legally able to consent to the relevant processing. Do not submit a child’s personal data without appropriate authority. Contact us if you believe such data was submitted.</p></Section>
  <Section title="9. Third parties and changes"><p>External websites and merchants have their own privacy practices. We are not responsible for those practices. We may update this policy to reflect operational or legal changes and will revise the date above.</p></Section>
  <Section title="10. Contact"><p>To ask a privacy question or exercise an applicable right, email {contact}. Please describe your request and jurisdiction; do not email sensitive identification documents unless requested through an appropriate secure method.</p></Section>
</>;
const frPrivacy = <>
  <Section title="1. Exploitant du site"><p>La présente Politique de confidentialité explique comment 2DOLIST USA LLC, société à responsabilité limitée de Floride, traite les données personnelles dans le cadre de BodyTrainingGuide.com.</p></Section>
  <Section title="2. Données que nous collectons"><p>Selon votre utilisation du site, nous pouvons recevoir :</p><Items><li>les informations que vous fournissez, telles que votre adresse e-mail et la source d’inscription à la newsletter, ou les informations envoyées par e-mail ;</li><li>les données techniques habituellement transmises lors d’une requête en ligne, telles que l’adresse IP, le navigateur, l’appareil, l’URL demandée, l’horodatage et les journaux de sécurité ou de serveur ;</li><li>les données d’authentification administrative des administrateurs autorisés ;</li><li>les informations reçues par un marchand tiers lorsque vous suivez un lien externe, traitées selon la politique de ce tiers.</li></Items><p>Le formulaire actuellement affiché sur la page publique de contact n’est relié à aucun traitement et n’envoie pas ses champs. Ne saisissez pas d’informations sensibles dans les formulaires du site.</p></Section>
  <Section title="3. Utilisations et finalités"><p>Nous pouvons utiliser les données pour fournir et sécuriser le site, répondre aux messages, traiter les inscriptions à la newsletter, diagnostiquer des erreurs, prévenir les abus, conserver les documents nécessaires, respecter la loi et constater ou défendre des droits. Lorsque cela est requis, la base juridique dépend du traitement et peut notamment être le consentement, l’exécution d’une demande, l’intérêt légitime ou une obligation légale.</p></Section>
  <Section title="4. Mesure d’audience et cookies"><p>Le frontend public actuel ne charge intentionnellement aucun outil de mesure d’audience, pixel publicitaire ou plateforme de gestion du consentement. Il ne dépose pas de cookie public facultatif de mesure d’audience ou de publicité. L’administration autorisée utilise un cookie d’authentification essentiel et son éditeur utilise le stockage local du navigateur. Consultez la Politique relative aux cookies. Si des technologies facultatives sont ajoutées, la présente politique et les contrôles de consentement requis devront être mis à jour avant leur activation pour les utilisateurs concernés.</p></Section>
  <Section title="5. Partage et traitements internationaux"><p>Nous pouvons communiquer des données à des prestataires d’hébergement, d’infrastructure, de sécurité, d’e-mail/newsletter et de services professionnels lorsque cela est nécessaire, ainsi qu’aux autorités ou à d’autres parties lorsque la loi l’exige ou l’autorise. L’exploitant étant établi aux États-Unis et le site étant international, les données peuvent être traitées hors de votre pays. Les garanties exigées par la loi applicable seront utilisées lorsqu’elles s’appliquent.</p></Section>
  <Section title="6. Conservation et sécurité"><p>Nous conservons les données seulement pendant la durée raisonnablement nécessaire à la finalité concernée, aux obligations légales, à la sécurité, aux litiges et à l’exercice des droits. La durée varie selon la donnée et le contexte. Nous appliquons des mesures techniques et organisationnelles raisonnables, mais aucun système en ligne n’est totalement sécurisé.</p></Section>
  <Section title="7. Vos choix et droits"><p>Vos droits dépendent de la législation applicable et des circonstances. Ils peuvent notamment comprendre, selon le cas, l’accès, la rectification, la suppression, la limitation, l’opposition, la portabilité, le retrait du consentement et certains droits relatifs à la publicité ciblée ou au partage de données. Le retrait du consentement ne remet pas en cause les traitements antérieurs licites. Nous pouvons devoir vérifier une demande et conserver des informations lorsque la loi le permet ou l’exige.</p></Section>
  <Section title="Utilisateurs situés dans l’Espace économique européen"><p>Lorsque la réglementation européenne relative à la protection des données s’applique au traitement de vos données personnelles, vous pouvez disposer de droits supplémentaires prévus par la législation applicable, notamment selon le cas de droits d’accès, de rectification, d’effacement, de limitation, d’opposition et de portabilité.</p><p>Lorsqu’un traitement repose sur votre consentement, vous pouvez retirer ce consentement à tout moment.</p><p>L’existence et les modalités d’exercice de ces droits dépendent du traitement concerné et de la réglementation applicable.</p></Section>
  <Section title="8. Enfants"><p>Le site ne s’adresse pas aux enfants qui ne sont pas légalement en mesure de consentir au traitement concerné. Ne transmettez pas les données d’un enfant sans autorité appropriée. Contactez-nous si vous pensez que de telles données ont été transmises.</p></Section>
  <Section title="9. Tiers et modifications"><p>Les sites et marchands externes appliquent leurs propres pratiques. Nous n’en sommes pas responsables. Nous pouvons modifier cette politique pour tenir compte d’évolutions opérationnelles ou juridiques et actualiserons alors la date ci-dessus.</p></Section>
  <Section title="10. Contact"><p>Pour poser une question ou exercer un droit applicable, écrivez à {contact}. Précisez votre demande et votre juridiction ; n’envoyez pas de pièce d’identité sensible par e-mail sauf demande via une méthode sécurisée appropriée.</p></Section>
</>;

const enCookies = <>
  <Section title="What this policy covers"><p>This policy describes the browser storage and similar technologies actually used by the current BodyTrainingGuide frontend. Cookies are small data files stored by a browser; local storage is browser storage that is not automatically sent with each request.</p></Section>
  <Section title="Current technology inventory"><h3>Public website</h3><p>The current public frontend does not intentionally set optional analytics or advertising cookies and does not load Google Analytics, Google Tag Manager, Google Ads, AdSense, Meta Pixel, Microsoft Clarity, Amazon Associates scripts, advertising networks, affiliate-network scripts, tracking pixels, third-party embeds, or iframes. No consent-management platform (CMP) is currently installed because no optional public tracker is enabled.</p><h3>Newsletter</h3><p>The newsletter form sends the email address and a page/source label to the BodyTrainingGuide server endpoint when the user submits it. The frontend does not use a cookie, local storage, or session storage for this submission.</p><h3>Administration</h3><p>The restricted administration area uses an <code>admin_jwt</code> cookie to authenticate authorized administrators. It is essential to the requested administrative session. The administration post editor also uses local storage to preserve an editor draft. These technologies are not used to track public visitors or for advertising.</p></Section>
  <Section title="Server and third-party merchant data"><p>Hosting and security systems may process ordinary request data such as IP address, user agent, requested URL, and timestamps in server logs without using an optional browser cookie. If you follow a link to a third-party merchant, that party may use its own cookies under its own policy and controls; BodyTrainingGuide does not control those technologies.</p></Section>
  <Section title="Your controls and future changes"><p>You can delete or block browser storage through your browser settings, though blocking an essential administration cookie will prevent administrator login. If BodyTrainingGuide introduces optional analytics, advertising, embeds, or similar technologies, this inventory and any consent mechanism required by applicable law should be updated before those technologies are enabled for affected users.</p></Section>
  <Section title="Contact"><p>Questions about this policy may be sent to {contact}.</p></Section>
</>;
const frCookies = <>
  <Section title="Objet de cette politique"><p>Cette politique décrit le stockage dans le navigateur et les technologies similaires réellement utilisés par le frontend actuel de BodyTrainingGuide. Un cookie est un petit fichier de données enregistré par le navigateur ; le stockage local est un espace du navigateur qui n’est pas automatiquement envoyé avec chaque requête.</p></Section>
  <Section title="Inventaire actuel des technologies"><h3>Site public</h3><p>Le frontend public actuel ne dépose intentionnellement aucun cookie facultatif de mesure d’audience ou de publicité et ne charge pas Google Analytics, Google Tag Manager, Google Ads, AdSense, Meta Pixel, Microsoft Clarity, de script Amazon Associates, de régie publicitaire, de script de réseau d’affiliation, de pixel de suivi, d’intégration tierce ou d’iframe. Aucune plateforme de gestion du consentement (CMP) n’est actuellement installée puisqu’aucun traceur public facultatif n’est activé.</p><h3>Newsletter</h3><p>Lors de sa soumission, le formulaire de newsletter envoie l’adresse e-mail et un libellé de page/source au point d’accès serveur de BodyTrainingGuide. Le frontend n’utilise ni cookie, ni stockage local, ni stockage de session pour cet envoi.</p><h3>Administration</h3><p>L’espace d’administration restreint utilise un cookie <code>admin_jwt</code> pour authentifier les administrateurs autorisés. Il est essentiel à la session administrative demandée. L’éditeur d’articles de l’administration utilise également le stockage local pour conserver un brouillon. Ces technologies ne servent ni à suivre les visiteurs publics, ni à faire de la publicité.</p></Section>
  <Section title="Données serveur et marchands tiers"><p>Les systèmes d’hébergement et de sécurité peuvent traiter dans leurs journaux les données ordinaires d’une requête, telles que l’adresse IP, l’agent utilisateur, l’URL demandée et l’horodatage, sans cookie facultatif. Si vous suivez un lien vers un marchand tiers, celui-ci peut utiliser ses propres cookies selon sa politique et ses contrôles ; BodyTrainingGuide ne contrôle pas ces technologies.</p></Section>
  <Section title="Vos contrôles et évolutions futures"><p>Vous pouvez supprimer ou bloquer le stockage via les réglages de votre navigateur, mais bloquer le cookie administratif essentiel empêchera la connexion à l’administration. Si BodyTrainingGuide ajoute des outils facultatifs de mesure d’audience, publicité, intégration ou technologie similaire, cet inventaire et tout mécanisme de consentement exigé par la loi applicable devront être mis à jour avant leur activation pour les utilisateurs concernés.</p></Section>
  <Section title="Contact"><p>Vos questions sur cette politique peuvent être envoyées à {contact}.</p></Section>
</>;
const enLegal = <>
  <p>BodyTrainingGuide.com is operated by:</p>
  <address className="not-italic"><strong>2DOLIST USA LLC</strong><br />Florida Limited Liability Company</address>
  <p><strong>Florida Document Number:</strong><br />L25000481686</p>
  <p><strong>Principal Address:</strong><br />7901 4th St N, Ste 300<br />St. Petersburg, FL 33702<br />United States</p>
  <p><strong>Contact:</strong><br />{contact}</p>
  <Section title="About the website"><p>BodyTrainingGuide is an informational and educational website focused in particular on fitness, strength training, exercise, and nutrition.</p><p>Unless expressly stated otherwise, BodyTrainingGuide does not directly sell products presented in its content. Some links may be affiliate links through which 2DOLIST USA LLC may receive compensation from a third party.</p></Section>
</>;
const frLegal = <>
  <p>Le site BodyTrainingGuide.com est exploité par :</p>
  <address className="not-italic"><strong>2DOLIST USA LLC</strong><br />Société à responsabilité limitée constituée selon le droit de l’État de Floride, États-Unis.</address>
  <p><strong>Florida Document Number :</strong><br />L25000481686</p>
  <p><strong>Adresse principale :</strong><br />7901 4th St N, Ste 300<br />St. Petersburg, FL 33702<br />États-Unis</p>
  <p><strong>Contact :</strong><br />{contact}</p>
  <Section title="À propos du site"><p>BodyTrainingGuide est un site d’information et d’éducation consacré notamment au fitness, à la musculation, à l’entraînement et à la nutrition.</p><p>Sauf indication expresse contraire, BodyTrainingGuide ne vend pas directement les produits présentés dans ses contenus.</p><p>Certains liens peuvent être des liens affiliés permettant à 2DOLIST USA LLC de percevoir une rémunération auprès d’un tiers.</p></Section>
</>;

const documents: Record<Locale, Record<LegalPageKey, { title: string; content: ReactNode }>> = {
  en: {
    terms: { title: 'Terms of Use', content: enTerms },
    medical: { title: 'Medical Disclaimer', content: enMedical },
    affiliate: { title: 'Affiliate Disclosure', content: enAffiliate },
    privacy: { title: 'Privacy Policy', content: enPrivacy },
    cookies: { title: 'Cookie Policy', content: enCookies },
    legal: { title: 'Legal Notice', content: enLegal }
  },
  fr: {
    terms: { title: "Conditions d’utilisation", content: frTerms },
    medical: { title: 'Avertissement médical', content: frMedical },
    affiliate: { title: "Information sur les liens d’affiliation", content: frAffiliate },
    privacy: { title: 'Politique de confidentialité', content: frPrivacy },
    cookies: { title: 'Politique relative aux cookies', content: frCookies },
    legal: { title: 'Mentions légales', content: frLegal }
  }
};

export const legalDocumentTitles: Record<Locale, Record<LegalPageKey, string>> = {
  en: { terms: 'Terms of Use', medical: 'Medical Disclaimer', affiliate: 'Affiliate Disclosure', privacy: 'Privacy Policy', cookies: 'Cookie Policy', legal: 'Legal Notice' },
  fr: { terms: "Conditions d’utilisation", medical: 'Avertissement médical', affiliate: 'Affiliation', privacy: 'Politique de confidentialité', cookies: 'Cookies', legal: 'Mentions légales' }
};

export function LegalDocument({ locale, pageKey }: { locale: Locale; pageKey: LegalPageKey }) {
  const document = documents[locale][pageKey];
  return <LegalPageLayout title={document.title} updatedLabel={locale === 'fr' ? FR_DATE : EN_DATE}>{document.content}</LegalPageLayout>;
}
